### ISSUE TITLE
Error: Command failed: grep -c '3[.]0863[35]' wordcount.log grep: wordcount.log: No such file or directory

### ISSUE THREAD

**Issue by jakepog** [Aerijo/latex-wordcount#3]
All package commands are either unresponsive and reduce no output, or throw the following error. Only 'Document wordcount (more accurate)' produces any output, which is the following. 

1. Open .tex file
2. Run 'Document wordcount (more accurate)'

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.14.1
**Thrown From**: [latex-wordcount](https://github.com/Aerijo/latex-wordcount) package 0.6.0

### Stack Trace

Uncaught Error: Notification must be created with string message: Error: Command failed: grep -c '3[.]0863[35]' wordcount.log
grep: wordcount.log: No such file or directory

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Notification must be created with string message: Error: Command failed: grep -c '3[.]0863[35]' wordcount.log
grep: wordcount.log: No such file or directory

    at Notification.validate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1216592)
    at new Notification (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1216531)
    at NotificationManager.addError (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:327325)
    at child_process.exec (/packages/latex-wordcount/lib/word-tools.js:79:29)
    at ChildProcess.exithandler (child_process.js:294:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

### Commands

```
  2x -6:47 core:move-down (input.hidden-input)
     -6:44.8.0 core:confirm (input.hidden-input)
     -6:44.7.0 latex-wordcount:document-wordcount (input.hidden-input)
     -4:34.9.0 latex:clean (input.hidden-input)
  4x -2:00.1.0 core:backspace (input.hidden-input)
     -0:33.9.0 command-palette:toggle (input.hidden-input)
     -0:28.9.0 core:confirm (input.hidden-input)
     -0:28.9.0 latex-wordcount:file-wordcount (input.hidden-input)
     -0:18.3.0 command-palette:toggle (input.hidden-input)
  2x -0:12.6.0 core:move-down (input.hidden-input)
     -0:10.2.0 core:confirm (input.hidden-input)
     -0:10.2.0 latex-wordcount:document-wordcount (input.hidden-input)
     -0:08.7.0 command-palette:toggle (input.hidden-input)
  4x -0:05.2.0 core:move-down (input.hidden-input)
     -0:04.1.0 core:confirm (input.hidden-input)
     -0:04.1.0 latex-wordcount:document-wordcount-(more accurate) (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-latex-cite 0.3.2 
autocomplete-latex-references 0.3.1 
language-latex 1.2.0 
latex 0.50.0 
latex-wordcount 0.6.0 
pdf-view 0.71.0 
teletype 0.13.3 
```

**Comment by Aerijo** [comment]
That's weird, I tested it just now on Mojave and it still worked. I'll look into it.

- Can you see a file called `wordcount.log` anywhere? Does the project have something that moves generated files?
- What does running `texcount` in `Terminal` do?

**Comment by jakepog** [comment]
This issue was resolved by cleaning up $PATH. Once `Terminal` found `texcount` properly, then no worries!
